- name: ADD UNIT FOR PUMA.SERVICE
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: RESTART PUMA

- name: DB CONFIG
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: ENABLE PUMA
  systemd:
    name: puma
    enabled: yes
    daemon_reload: yes